name: Deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  Deploy-To-NPM:
    runs-on: ubuntu-latest
    name: Deploy to NPM
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: node --version
      - run: npm install -g npm@latest
      - run: npm --version
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm publish --provenance --access=public
